Fix flow detection when generating patterns without internal node (#283)
* Fix flow detection when generating patterns without internal node

This commit fixes `generate_from_graph` so that it correctly
constructs patterns from graphs that have no internal nodes (i.e.,
when the input set and output set are equal). In this case,
`find_flow` returns an empty flow, which should be distinguished from
`None`.

* Fix ruff

* Add missing type annotation

mypy says:
tests/test_generator.py:86: error: Need type annotation for "g"  [var-annotated]